### ISSUE TITLE
Vagrant up Failure join.sh

### ISSUE THREAD

**Issue by panyogesh** [nextbreakpoint/kubernetes-playground#16]
Getting the following error. Any idea on what went wrong.    

k8s2: TASK [k8s-worker : Copy join script] *******************************************
    k8s2: An exception occurred during task execution. To see the full traceback, use -vvv. The error was: If you are using a module and expect the file to exist on the remote, see the remote_src option
    k8s2: fatal: [localhost]: FAILED! => {"changed": false, "msg": "Could not find or access '/vagrant/join.sh' on the Ansible Controller.\nIf you are using a module and expect the file to exist on the remote, see the remote_src option"}
    k8s2:
    k8s2: PLAY RECAP *********************************************************************
    k8s2: localhost                  : ok=30   changed=22   unreachable=0    failed=1    skipped=0    rescued=0    ignored=0

**Comment by nextbreakpoint** [comment]
I'll have a look

**Comment by nextbreakpoint** [comment]
Hi panygesh,
Could you tell me what version of Vagrant and VirtualBox are you using?

Also, I have prepared an update, which is in this branch: 
https://github.com/nextbreakpoint/kubernetes-playground/tree/wip

Would you mind to try this one and let me know how it goes?

**Comment by panyogesh** [comment]
I guess its some package installation related to metrics (on my machine) . The precise error is  :
   k8s1: TASK [k8s-master : Modify Metrics server deployment] ***************************
    k8s1: fatal: [localhost]: FAILED! => {"changed": false, "msg": "Path /var/tmp/metrics-server/deploy/kubernetes/metrics-server- 
   deployment.yaml does not exist !", "rc": 257}

Just after that the join file creation was there which failed. 
If I comment the metric related (ansible script) it all works fine for me...

So its metrics related and seems some missing package on my machine. Thanks for looking up.

**Comment by nextbreakpoint** [comment]
did you try using the branch wip? I think that it should fix the issue with the metrics server (and also other issues)

**Comment by panyogesh** [comment]
Somehow I am getting same error with WIP as well. Following are some additional info :  
1.
$ vagrant version
Installed Version: 2.2.6
Latest Version: 2.2.14

2.
Virtual Box 6.0.24

3.
commit 7336aca36f16e71947c440032a28ad07535cf16e
Merge: 5242f7b cbbc702
Author: NextBreakpoint <nextbreakpoint@users.noreply.github.com>

Removing the following is solving the issue 
 - name: Modify Metrics server deployment
 - name: Change runAsRoot in Metrics server deployment
 - name: Print Metrics server deployment

**Comment by nextbreakpoint** [comment]
Hi panygesh, the commit 7336aca is on master branch. You have to switch to wip and try commit [9ece515](https://github.com/nextbreakpoint/kubernetes-playground/commit/9ece5157fef91c677d41ebdd3fc48f6e1d60ddf3)

```
git clone https://github.com/nextbreakpoint/kubernetes-playground.git
git fetch --all
git checkout wip
```

I think it will solve your issue. I still have some work to do, but I'll merge wip into mater soon.

**Comment by panyogesh** [comment]
Perfect and many Thanks. Its all working fine.

**Comment by nextbreakpoint** [comment]
ok. closing the issue
